select xmlserialize(content
         xmlconcat(xmlpi(name "xml-stylesheet", 'type="text/xsl" href="fleet.xsl"'),
                   xmlcomment('Generated by Nimbus Air'),
                   xmlelement("note", xmlcdata('Fares < $500 & taxes')))
         indent) as fragments
from   dual;
