-- Installs the Nimbus Air sample schema of the book in the current schema.
-- Connect as the schema owner (NIMBUS, created by create-user.sql) and run:
--   sql nimbus@localhost:1521/FREEPDB1 @install.sql
-- Run uninstall.sql first to install it again from the start.
set feedback off
prompt Creating the tables...
@@schema.sql
prompt Loading the data...
@@data.sql
alter table departments add constraint departments_manager_fk foreign key (manager_id) references employees;
-- identity columns continue after the highest value loaded
alter table routes    modify route_id    generated by default on null as identity (start with limit value);
alter table flights   modify flight_id   generated by default on null as identity (start with limit value);
alter table customers modify customer_id generated by default on null as identity (start with limit value);
alter table bookings  modify booking_id  generated by default on null as identity (start with limit value);
alter table tickets   modify ticket_id   generated by default on null as identity (start with limit value);
alter table payments  modify payment_id  generated by default on null as identity (start with limit value);
alter table reviews   modify review_id   generated by default on null as identity (start with limit value);
@@comments.sql
prompt Gathering optimizer statistics...
exec dbms_stats.gather_schema_stats(user)
set feedback on
prompt Nimbus Air is installed.
select table_name, num_rows from user_tables order by table_name;
