-- Nimbus Air sample schema: the tables of the book (Chapter 5).
-- Run as NIMBUS from install.sql.

create table countries (
  country_code   char(2)       constraint countries_pk primary key,
  country_name   varchar2(60)  not null,
  region         varchar2(30)  not null,
  currency_code  char(3)       not null
);

create table airports (
  airport_code   char(3)       constraint airports_pk primary key,
  airport_name   varchar2(80)  not null,
  city           varchar2(40)  not null,
  country_code   char(2)       not null constraint airports_country_fk references countries,
  time_zone      varchar2(40)  not null,
  latitude       number(8,5)   not null,
  longitude      number(8,5)   not null,
  elevation_ft   number(5),
  is_hub         boolean       default false not null
);

create table aircraft_types (
  type_code       varchar2(4)   constraint aircraft_types_pk primary key,
  manufacturer    varchar2(30)  not null,
  model           varchar2(30)  not null,
  seats_business  number(3)     not null,
  seats_economy   number(3)     not null,
  range_km        number(5)     not null,
  cruise_kmh      number(4)     not null
);

create table aircraft (
  tail_number   varchar2(8)   constraint aircraft_pk primary key,
  type_code     varchar2(4)   not null constraint aircraft_type_fk references aircraft_types,
  delivered_on  date          not null,
  status        varchar2(12)  default 'ACTIVE' not null
                constraint aircraft_status_ck check (status in ('ACTIVE', 'MAINTENANCE', 'RETIRED'))
);

create table routes (
  route_id       number        generated by default on null as identity constraint routes_pk primary key,
  origin         char(3)       not null constraint routes_origin_fk references airports,
  destination    char(3)       not null constraint routes_destination_fk references airports,
  distance_km    number(5)     not null,
  block_minutes  number(4)     not null,
  constraint routes_uk unique (origin, destination),
  constraint routes_ends_ck check (origin <> destination)
);

create table flights (
  flight_id            number        generated by default on null as identity constraint flights_pk primary key,
  flight_no            varchar2(6)   not null,
  route_id             number        not null constraint flights_route_fk references routes,
  tail_number          varchar2(8)   not null constraint flights_aircraft_fk references aircraft,
  scheduled_departure  timestamp with time zone not null,
  scheduled_arrival    timestamp with time zone not null,
  actual_departure     timestamp with time zone,
  actual_arrival       timestamp with time zone,
  status               varchar2(10)  default 'SCHEDULED' not null
                       constraint flights_status_ck check (status in ('SCHEDULED', 'ARRIVED', 'CANCELLED'))
);
create index flights_route_ix on flights (route_id);
create index flights_departure_ix on flights (scheduled_departure);

create table departments (
  department_id    number(4)     constraint departments_pk primary key,
  department_name  varchar2(40)  not null,
  base_airport     char(3)       not null constraint departments_airport_fk references airports,
  manager_id       number(6)
);

create table employees (
  employee_id     number(6)     constraint employees_pk primary key,
  first_name      varchar2(30)  not null,
  last_name       varchar2(30)  not null,
  email           varchar2(30)  not null constraint employees_email_uk unique,
  job_title       varchar2(40)  not null,
  department_id   number(4)     not null constraint employees_department_fk references departments,
  manager_id      number(6)     constraint employees_manager_fk references employees,
  hire_date       date          not null,
  salary          number(8,2)   not null constraint employees_salary_ck check (salary > 0),
  commission_pct  number(3,2),
  base_airport    char(3)       not null constraint employees_airport_fk references airports
);
create index employees_manager_ix on employees (manager_id);
create index employees_department_ix on employees (department_id);

create table crew_assignments (
  flight_id    number        constraint crew_flight_fk references flights,
  employee_id  number(6)     constraint crew_employee_fk references employees,
  crew_role    varchar2(15)  not null,
  constraint crew_assignments_pk primary key (flight_id, employee_id)
);
create index crew_employee_ix on crew_assignments (employee_id);

create table customers (
  customer_id    number        generated by default on null as identity constraint customers_pk primary key,
  first_name     varchar2(30)  not null,
  last_name      varchar2(30)  not null,
  email          varchar2(60)  not null constraint customers_email_uk unique,
  phone          varchar2(20),
  date_of_birth  date,
  country_code   char(2)       constraint customers_country_fk references countries,
  joined_on      date          default sysdate not null,
  loyalty        json
);

create table bookings (
  booking_id     number        generated by default on null as identity constraint bookings_pk primary key,
  booking_ref    char(6)       not null constraint bookings_ref_uk unique,
  customer_id    number        not null constraint bookings_customer_fk references customers,
  booked_at      timestamp     not null,
  status         varchar2(10)  not null
                 constraint bookings_status_ck check (status in ('CONFIRMED', 'COMPLETED', 'CANCELLED')),
  total_amount   number(10,2)  not null,
  currency_code  char(3)       default 'USD' not null
);
create index bookings_customer_ix on bookings (customer_id);

create table tickets (
  ticket_id   number        generated by default on null as identity constraint tickets_pk primary key,
  booking_id  number        not null constraint tickets_booking_fk references bookings,
  flight_id   number        not null constraint tickets_flight_fk references flights,
  cabin       varchar2(8)   not null constraint tickets_cabin_ck check (cabin in ('BUSINESS', 'ECONOMY')),
  seat_no     varchar2(4)   not null,
  fare        number(8,2)   not null,
  checked_in  boolean       default false not null
);
create index tickets_booking_ix on tickets (booking_id);
create index tickets_flight_ix on tickets (flight_id);

create table payments (
  payment_id      number        generated by default on null as identity constraint payments_pk primary key,
  booking_id      number        not null constraint payments_booking_fk references bookings,
  paid_at         timestamp     not null,
  payment_method  varchar2(15)  not null,
  amount          number(10,2)  not null
);
create index payments_booking_ix on payments (booking_id);

create table reviews (
  review_id    number          generated by default on null as identity constraint reviews_pk primary key,
  flight_id    number          not null constraint reviews_flight_fk references flights,
  customer_id  number          not null constraint reviews_customer_fk references customers,
  rating       number(1)       not null constraint reviews_rating_ck check (rating between 1 and 5),
  review_text  varchar2(1000)  not null,
  reviewed_on  date            not null
);
